import type { ApplyCardTheme } from "./ApplyCard";

export const applyCardThemes: Record<string, ApplyCardTheme> = {
  cyprus: {
    accentText: "text-blue-600",
    accentBg: "bg-blue-600",
    accentSoftBg: "bg-blue-50",
    accentIcon: "text-blue-400",
    accentFocus: "focus:ring-blue-500/20 focus:border-blue-400",
    buttonHover: "hover:bg-blue-600",
    secureCardBg: "bg-blue-600",
    secureText: "text-white",
    secureSubtext: "text-blue-100",
    secureBlob: "bg-blue-700/40",
  },
  northernCyprus: {
    accentText: "text-blue-600",
    accentBg: "bg-blue-600",
    accentSoftBg: "bg-blue-50",
    accentIcon: "text-blue-400",
    accentFocus: "focus:ring-blue-500/20 focus:border-blue-400",
    buttonHover: "hover:bg-blue-600",
    secureCardBg: "bg-blue-600",
    secureText: "text-white",
    secureSubtext: "text-blue-100",
    secureBlob: "bg-blue-700/40",
  },
  malaysia: {
    accentText: "text-emerald-600",
    accentBg: "bg-emerald-600",
    accentSoftBg: "bg-emerald-50",
    accentIcon: "text-emerald-400",
    accentFocus: "focus:ring-emerald-500/20 focus:border-emerald-400",
    buttonHover: "hover:bg-emerald-600",
    secureCardBg: "bg-emerald-600",
    secureText: "text-white",
    secureSubtext: "text-emerald-100",
    secureBlob: "bg-emerald-700/40",
  },
  turkey: {
    accentText: "text-red-600",
    accentBg: "bg-red-600",
    accentSoftBg: "bg-red-50",
    accentIcon: "text-red-400",
    accentFocus: "focus:ring-red-500/20 focus:border-red-400",
    buttonHover: "hover:bg-red-600",
    secureCardBg: "bg-red-600",
    secureText: "text-white",
    secureSubtext: "text-red-100",
    secureBlob: "bg-red-700/40",
  },
  uganda: {
    accentText: "text-amber-600",
    accentBg: "bg-amber-500",
    accentSoftBg: "bg-amber-50",
    accentIcon: "text-amber-400",
    accentFocus: "focus:ring-amber-500/20 focus:border-amber-400",
    buttonHover: "hover:bg-amber-500",
    secureCardBg: "bg-amber-500",
    secureText: "text-white",
    secureSubtext: "text-amber-100",
    secureBlob: "bg-amber-700/35",
  },
  rwanda: {
    accentText: "text-emerald-700",
    accentBg: "bg-emerald-700",
    accentSoftBg: "bg-emerald-50",
    accentIcon: "text-emerald-500",
    accentFocus: "focus:ring-emerald-500/20 focus:border-emerald-500",
    buttonHover: "hover:bg-emerald-700",
    secureCardBg: "bg-emerald-700",
    secureText: "text-white",
    secureSubtext: "text-emerald-100",
    secureBlob: "bg-emerald-900/30",
  },
};